name: dns_changer
description: "DNS Changer for Android - free DNS profiles + private license-based subscription with Cloudflare admin panel."
publish_to: "none"
version: 1.0.1+10001

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
