import '../models/dns_server.dart';

/// Built-in free/public DNS servers with categories and rich metadata.
const List<DnsServer> freeDnsServers = [
  // 🎮 Gaming & Anti-Sanction / Regional DNS
  DnsServer(
    id: 'radar',
    name: 'Radar Game',
    description: 'مخصوص بازی‌های آنلاین، کاهش پینگ و رفع تحریم',
    addresses: ['10.202.10.10', '10.202.10.11'],
    country: 'IR',
    category: DnsCategory.gaming,
    tags: ['Gaming', 'Anti-Sanction', 'Low-Ping'],
  ),
  DnsServer(
    id: 'electro',
    name: 'Electro',
    description: 'رفع تحریم سرویس‌های گیمینگ، دولوپری و عمومی',
    addresses: ['78.157.42.100', '78.157.42.101'],
    country: 'IR',
    category: DnsCategory.gaming,
    tags: ['Gaming', 'Developers', 'Anti-Sanction'],
  ),
  DnsServer(
    id: 'shecan',
    name: 'Shecan (شکن)',
    description: 'تحریم‌شکن اینترنتی برای دسترسی به سایت‌های تحریم‌شده',
    addresses: ['178.22.122.100', '185.51.200.2'],
    country: 'IR',
    category: DnsCategory.gaming,
    tags: ['Anti-Sanction', 'Popular', 'IR'],
  ),
  DnsServer(
    id: '403',
    name: '403.online',
    description: 'سرویس رفع تحریم برای برنامه‌نویسان و گیمرها',
    addresses: ['10.202.10.202', '10.202.10.102'],
    country: 'IR',
    category: DnsCategory.gaming,
    tags: ['Anti-Sanction', 'Developers', 'Gaming'],
  ),
  DnsServer(
    id: 'begzar',
    name: 'Begzar (بگذر)',
    description: 'دی‌ان‌اس تحریم‌شکن ایرانی سریع و پایدار',
    addresses: ['185.55.226.26', '185.55.225.25'],
    country: 'IR',
    category: DnsCategory.gaming,
    tags: ['Anti-Sanction', 'IR'],
  ),
  DnsServer(
    id: 'pishgam',
    name: 'Pishgam DNS',
    description: 'دی‌ان‌اس پیشگام برای گیمینگ و کاهش لگ',
    addresses: ['5.202.100.100', '5.202.100.101'],
    country: 'IR',
    category: DnsCategory.gaming,
    tags: ['Gaming', 'Low-Ping'],
  ),
  DnsServer(
    id: 'shatel',
    name: 'Shatel DNS',
    description: 'سرور دی‌ان‌اس پرسرعت شبکه شاتل',
    addresses: ['85.15.1.14', '85.15.1.15'],
    country: 'IR',
    category: DnsCategory.gaming,
    tags: ['ISP', 'IR', 'Fast'],
  ),

  // ⚡ Fast & General Public DNS
  DnsServer(
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'سریع‌ترین دی‌ان‌اس عمومی و حامی حریم خصوصی. 1.1.1.1',
    addresses: ['1.1.1.1', '1.0.0.1', '2606:4700:4700::1111', '2606:4700:4700::1001'],
    country: 'Global',
    category: DnsCategory.general,
    tags: ['Fastest', 'Privacy', 'Global'],
    dohUrl: 'https://cloudflare-dns.com/dns-query',
    dotHost: 'one.one.one.one',
  ),
  DnsServer(
    id: 'google',
    name: 'Google Public DNS',
    description: 'دی‌ان‌اس پایدار و معتبر گوگل با پوشش سرتاسری. 8.8.8.8',
    addresses: ['8.8.8.8', '8.8.4.4', '2001:4860:4860::8888', '2001:4860:4860::8844'],
    country: 'Global',
    category: DnsCategory.general,
    tags: ['Reliable', 'Google', 'Global'],
    dohUrl: 'https://dns.google/dns-query',
    dotHost: 'dns.google',
  ),
  DnsServer(
    id: 'quad9',
    name: 'Quad9',
    description: 'دی‌ان‌اس امنیتی رایگان با مسدودسازی بدافزارها و فیشینگ',
    addresses: ['9.9.9.9', '149.112.112.112', '2620:fe::fe', '2620:fe::9'],
    country: 'Global',
    category: DnsCategory.general,
    tags: ['Security', 'Privacy', 'Global'],
    dohUrl: 'https://dns.quad9.net/dns-query',
    dotHost: 'dns.quad9.net',
  ),
  DnsServer(
    id: 'opendns',
    name: 'Cisco OpenDNS',
    description: 'دی‌ان‌اس قدرتمند و باسابقه سیسکو با سرعت و پایداری بالا',
    addresses: ['208.67.222.222', '208.67.220.220'],
    country: 'Global',
    category: DnsCategory.general,
    tags: ['Cisco', 'Fast', 'Enterprise'],
    dohUrl: 'https://doh.opendns.com/dns-query',
    dotHost: 'dns.opendns.com',
  ),
  DnsServer(
    id: 'controld',
    name: 'Control D (Uncensored)',
    description: 'دی‌ان‌اس فوق‌سریع بدون محدودیت و بدون لاگینگ',
    addresses: ['76.76.2.0', '76.76.10.0', '2606:1a40::', '2606:1a40:1::'],
    country: 'Global',
    category: DnsCategory.general,
    tags: ['Fast', 'NoLogs', 'Modern'],
    dohUrl: 'https://freedns.controld.com/p0',
    dotHost: 'p0.freedns.controld.com',
  ),
  DnsServer(
    id: 'level3',
    name: 'Level3 / CenturyLink',
    description: 'سرورهای اصلی بک‌بون اینترنت جهانی',
    addresses: ['4.2.2.1', '4.2.2.2', '4.2.2.3', '4.2.2.4'],
    country: 'US',
    category: DnsCategory.general,
    tags: ['Backbone', 'Tier1'],
  ),
  DnsServer(
    id: 'dnswatch',
    name: 'DNS.WATCH',
    description: 'دی‌ان‌اس آلمانی بدون لاگ و سانسور با احترام به حریم خصوصی',
    addresses: ['84.200.69.80', '84.200.70.40', '2001:1608:10:25::1c04:b12f'],
    country: 'DE',
    category: DnsCategory.general,
    tags: ['Privacy', 'NoLogs', 'Germany'],
  ),
  DnsServer(
    id: 'gcore',
    name: 'G-Core DNS',
    description: 'دی‌ان‌اس بین‌المللی با شبکه Anycast توزیع شده',
    addresses: ['95.85.95.85', '2.56.220.2'],
    country: 'Global',
    category: DnsCategory.general,
    tags: ['Anycast', 'Fast'],
  ),
  DnsServer(
    id: 'verisign',
    name: 'Verisign Public DNS',
    description: 'دی‌ان‌اس امن و پایدار شرکت وری‌ساین',
    addresses: ['64.6.64.6', '64.6.65.6', '2620:74:1b::1:1'],
    country: 'US',
    category: DnsCategory.general,
    tags: ['Verisign', 'Stable'],
  ),

  // 🛡️ Ad-Blocking & Privacy DNS
  DnsServer(
    id: 'adguard',
    name: 'AdGuard DNS',
    description: 'مسدودسازی تبلیغات، ترکرها و پاپ‌آپ‌ها در کل گوشی',
    addresses: ['94.140.14.14', '94.140.15.15', '2a10:50c0::ad1:ff', '2a10:50c0::ad2:ff'],
    country: 'Global',
    category: DnsCategory.security,
    tags: ['AdBlock', 'Privacy', 'Popular'],
    dohUrl: 'https://dns.adguard-dns.com/dns-query',
    dotHost: 'dns.adguard-dns.com',
  ),
  DnsServer(
    id: 'mullvad',
    name: 'Mullvad AdBlock',
    description: 'مسدودسازی تبلیغات و بدافزارها از سازنده VPN مولواد',
    addresses: ['194.242.2.2', '193.19.108.2', '2a07:e340::2'],
    country: 'SE',
    category: DnsCategory.security,
    tags: ['AdBlock', 'Mullvad', 'Privacy'],
    dohUrl: 'https://adblock.doh.mullvad.net/dns-query',
    dotHost: 'adblock.doh.mullvad.net',
  ),
  DnsServer(
    id: 'cleanbrowsing_sec',
    name: 'CleanBrowsing Security',
    description: 'مسدودسازی سایت‌های مخرب، فیشینگ و بدافزارها',
    addresses: ['185.228.168.9', '185.228.169.9', '2a0d:2a00:1::2', '2a0d:2a00:2::2'],
    country: 'Global',
    category: DnsCategory.security,
    tags: ['Malware-Block', 'Phishing-Protection'],
    dohUrl: 'https://doh.cleanbrowsing.org/doh/security-filter/',
    dotHost: 'security-filter-dns.cleanbrowsing.org',
  ),
  DnsServer(
    id: 'nextdns',
    name: 'NextDNS Public',
    description: 'دی‌ان‌اس ابری فوق‌سریع و مدرن با محافظت امنیتی',
    addresses: ['45.90.28.0', '45.90.30.0', '2a07:a8c0::', '2a07:a8c1::'],
    country: 'Global',
    category: DnsCategory.security,
    tags: ['Modern', 'Security', 'Fast'],
    dohUrl: 'https://dns.nextdns.io',
    dotHost: 'dns.nextdns.io',
  ),
  DnsServer(
    id: 'libredns',
    name: 'LibreDNS',
    description: 'دی‌ان‌اس متن‌باز، بدون لاگ و محافظ حریم خصوصی',
    addresses: ['116.202.176.26'],
    country: 'DE',
    category: DnsCategory.security,
    tags: ['OpenSource', 'NoLogs'],
  ),

  // 👨‍👩‍👧 Family & Safe Search DNS
  DnsServer(
    id: 'cloudflare_family',
    name: 'Cloudflare Family 1.1.1.3',
    description: 'مسدودسازی بدافزارها و محتوای غیراخلاقی و نامناسب',
    addresses: ['1.1.1.3', '1.0.0.3', '2606:4700:4700::1113', '2606:4700:4700::1003'],
    country: 'Global',
    category: DnsCategory.family,
    tags: ['Family', 'SafeSearch', 'ParentalControl'],
    dohUrl: 'https://family.cloudflare-dns.com/dns-query',
    dotHost: 'family.cloudflare-dns.com',
  ),
  DnsServer(
    id: 'adguard_family',
    name: 'AdGuard Family Protection',
    description: 'مسدودسازی تبلیغات + مسدودسازی سایت‌های نامناسب برای کودکان',
    addresses: ['94.140.14.15', '94.140.15.16', '2a10:50c0::bad1:ff', '2a10:50c0::bad2:ff'],
    country: 'Global',
    category: DnsCategory.family,
    tags: ['Family', 'AdBlock', 'SafeChild'],
    dohUrl: 'https://dns-family.adguard-dns.com/dns-query',
    dotHost: 'family.adguard-dns.com',
  ),
  DnsServer(
    id: 'cleanbrowsing_family',
    name: 'CleanBrowsing Family Filter',
    description: 'قفل جستجوی امن در گوگل و یوتیوب و مسدودسازی محتوای بزرگسالان',
    addresses: ['185.228.168.168', '185.228.169.168', '2a0d:2a00:1::', '2a0d:2a00:2::'],
    country: 'Global',
    category: DnsCategory.family,
    tags: ['Family', 'SafeSearch', 'CleanBrowsing'],
    dohUrl: 'https://doh.cleanbrowsing.org/doh/family-filter/',
    dotHost: 'family-filter-dns.cleanbrowsing.org',
  ),
  DnsServer(
    id: 'opendns_family',
    name: 'OpenDNS FamilyShield',
    description: 'حفاظت پیش‌فرض خانواده توسط سیسکو',
    addresses: ['208.67.222.123', '208.67.220.123'],
    country: 'Global',
    category: DnsCategory.family,
    tags: ['Family', 'Cisco'],
    dohUrl: 'https://doh.familyshield.opendns.com/dns-query',
  ),
];
